version: '3.3'

services:
  app:
    tty: true # keep the container running
    restart: always
    image: ticket-booking
    container_name: ticket-booking
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    networks:
      - application
    depends_on:
      - db
    volumes:
      - .:/app
    command: air -c .air.toml
    
  db:
    image: postgres:12-alpine
    container_name: ticket-booking-db
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  application:

volumes:
  postgres-data:
